name: revere
base: core22
version: '0.1.4'
summary: Open source, cross platform ONVIF compatible video surveillance.
description: |
  A free, open source, onvif compatible, cross platform video surveillance system designed to run unobtrusively on standard desktop computers.
grade: stable
confinement: strict

apps:
  revere:
    command: usr/local/revere/revere
    plugs: [process-control, desktop, desktop-legacy, spi, home, network, network-bind, network-status, opengl, unity7, wayland]
    extensions: [gnome]
  vision:
    command: usr/local/revere/vision
    plugs: [process-control, desktop, desktop-legacy, spi, home, network, network-bind, network-status, opengl, unity7, wayland]
    extensions: [gnome]

parts:
  revere:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
    source-type: git
    source: https://github.com/dicroce/revere
    build-packages:
      - git
      - zip
      - unzip
      - tar
      - cmake
      - pkg-config
      - nasm
      - libxinerama-dev
      - libxcursor-dev
      - xorg-dev
      - libglu1-mesa-dev
      - bison
      - python3-distutils
      - flex
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - libunwind-dev
      - libcurl4-openssl-dev
      - build-essential
    stage-packages:
      - libcurl4
      - lzip
      - libxinerama1
      - libxcursor1
      - libglu1-mesa
      - libayatana-appindicator3-1
      - libunwind8
      - mesa-utils
      - libglu1-mesa
      - libgl1-mesa-glx
      - libglx0
      - libgl1-mesa-dri
      - xserver-xorg-video-all
